# Generated by Django 4.2.16 on 2024-09-21 16:27

import cowork.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkingspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cowork.storage.SupabaseStorage(), upload_to='workspace_images/'),
        ),
    ]
