# Generated by Django 4.2.16 on 2024-09-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkingspace', '0002_alter_description_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceform',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
